# PROJECT SPECIFICATIONS
language: php
php:
- 7.0
branches:
  except:
  - "/^*-v[0-9]/"

# WORKSPACE CONFIGURATION
before_script:
- phpenv config-rm xdebug.ini
- mkdir plugins
- wget -O plugins/DevTools.phar https://github.com/PocketMine/DevTools/releases/download/v1.11.0/DevTools_v1.11.0.phar
- pecl install channel://pecl.php.net/pthreads-3.1.5
- pecl install channel://pecl.php.net/weakref-0.3.1
- echo | pecl install channel://pecl.php.net/yaml-2.0.0RC7

# PROJECT BUILDING WITH DEVTOOLS
script:
- php tests/TravisTest.php

# UPLOADING TO RELEASES WEBSITE
after_success:
- cd /home/travis/build
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- mv ImagicalCorp keithkfng
- git clone --branch=gh-pages https://github.com/ImagicalCorp/ImagicalMine
- cp /home/travis/build/keithkfng/ImagicalMine/plugins/DevTools//ImagicalMine_1.45.phar /home/travis/build/ImagicalMine/ImagicalMine-$TRAVIS_JOB_ID.phar
- cp /home/travis/build/keithkfng/ImagicalMine/plugins/DevTools//ImagicalMine_1.45.phar /home/travis/build/ImagicalMine/service-download/ImagicalMine.phar
- cd ImagicalMine
- git add ImagicalMine-$TRAVIS_JOB_ID.phar
- git add service-download/ImagicalMine.phar
- chmod 777 _makeindex.sh
- ./_makeindex.sh
- echo >> list.txt
- echo "This is a directory listing of the root directory of the release download website. Copy the file name and paste it in the URL bar after deleting \"list.txt\". You can also alternatively download files using a shell script by downloading the file from http://imagicalcorp.github.io/ImagicalMine/service-download/ImagicalMine.phar" >> list.txt
- git commit -am "Added latest build"
- git push https://ImagicalCorporation:$GITHUB_API_KEY@github.com/ImagicalCorp/ImagicalMine gh-pages &>secret
